[pytest]
addopts = -ra -q
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: UI-тесты (часто медленные, можно отключать с -m "not ui")
    smoke: Smoke-тесты (быстрая проверка ключевых сценариев)
    regression: Регрессионные тесты (полный набор позитивных и негативных кейсов)
